import { browser } from "wxt/browser";

import DEFAULT_MENU_CONFIGS from "../../../utilities/default-menu-configs.json";

import utilities from "scripts/helpers/utilities";
import {
  ConvertEditableText,
  CopyPlainTextToClipboard,
  PingContentScript,
} from "scripts/helpers/messages";

export const CONFIG_STORAGE_KEY = "menu-configs";

export const MENU_CONTEXTS = ["selection", "editable"];

export const GetMenuId = (utility, context) =>
  `${utility}-${context}`.toLowerCase();

/**
 * Resolves a context menu item ID (as generated by `GetMenuId()`)
 * back to its utility name and menu context
 * @param {string} menuItemId the ID of the clicked context menu item
 * @returns {{ utility: string, context: string } | null}
 */
export const ParseMenuItemId = (menuItemId) => {
  if (typeof menuItemId !== "string") {
    return null;
  }

  for (const context of MENU_CONTEXTS) {
    const suffix = `-${context}`;
    if (menuItemId.endsWith(suffix)) {
      const utilityIdLower = menuItemId.slice(0, -suffix.length);
      const utility = Object.keys(utilities).find(
        (id) => id.toLowerCase() === utilityIdLower
      );

      if (utility) {
        return { utility, context };
      }
    }
  }

  return null;
};

/**
 * Ensures the content script is loaded in the given tab/frame,
 * injecting it via the `scripting` API when it is not already present
 * (Chrome/Edge register the content script at runtime; page access is
 * granted via `activeTab` when the user clicks a context menu item)
 * @param {number} tabId the ID of the tab
 * @param {number} frameId the ID of the frame within the tab
 */
export const EnsureContentScript = async (tabId, frameId = 0) => {
  try {
    await PingContentScript(tabId, frameId);
  } catch {
    // no message listener in the target frame, so the content script
    // is not loaded (it is registered at runtime for Chrome/Edge)
    if (typeof browser.scripting?.executeScript !== "function") {
      throw new Error("Unable to load content script (scripting API missing)");
    }

    await browser.scripting.executeScript({
      target: { tabId, frameIds: [frameId] },
      files: ["content-scripts/content.js"],
    });
  }
};

/**
 * Top-level handler for `contextMenus.onClicked` events
 * (MV3 service workers cannot use per-menu `onclick` callbacks;
 * this must be registered synchronously so menu clicks are handled
 * even when the background has been suspended and restarted)
 * @param {object} info the context menu click info
 * @param {object} tab the tab where the click occurred
 */
export const OnMenuClicked = async (info, tab) => {
  const parsed = ParseMenuItemId(info.menuItemId);
  if (parsed === null) {
    return;
  }

  const { utility, context } = parsed;

  if (typeof utilities[utility]?.["fn"] !== "function") {
    console.error(`Utility "${utility}" is invalid`);
    return;
  }

  const frameId = info.frameId ?? 0;
  await EnsureContentScript(tab.id, frameId);

  switch (context) {
    case "selection":
      await CopyPlainTextToClipboard(
        tab.id,
        utilities[utility]["fn"].call(null, info.selectionText)
      );
      break;

    case "editable":
      await ConvertEditableText(
        tab.id,
        frameId,
        info.targetElementId,
        utility
      );
      break;
  }
};

export const GetMenusForUtilities = () => {
  const menus = {};

  Object.entries(utilities).forEach(([id, { contexts }]) => {
    menus[id] = {
      id,
      possibleContexts: contexts,
      title: GetDefaultMenuTitle(id),
    };
  });

  // console.log("GetMenusForUtilities()", menus);
  return menus;
};

export const GetMenusWithConfigs = async () => {
  const menus = GetMenusForUtilities();
  const configs = await GetMenuConfigsFromStorage();
  const defaults = GetDefaultMenuConfigs();

  Object.keys(menus).forEach((id) => {
    if (!configs[id]) {
      console.warn("Missing Config for Menu", id);
    }

    menus[id] = {
      id,
      order: configs[id]?.["order"] ?? defaults[id]["order"],
      enabledContexts:
        configs[id]?.["enabledContexts"] ?? defaults[id]["enabledContexts"],
      possibleContexts: menus[id]["possibleContexts"],
      title: configs[id]?.["title"] ?? menus[id]["title"],
    };
  });

  // console.log("GetMenusWithConfigs()", menus);
  return menus;
};

export const GetDefaultMenuConfigs = () => {
  const configs = {};

  Object.keys(GetMenusForUtilities()).forEach((id) => {
    configs[id] = DEFAULT_MENU_CONFIGS[id] ?? {
      order: null,
      enabledContexts: [],
    };
  });

  // fill in the order for menus without a default order (placing them at the end)
  let order = Array.from(Object.values(configs))
    .map((menu) => menu["order"])
    .filter((order) => order > 0)
    .sort((a, b) => a - b)
    .pop();

  Object.entries(configs).forEach(([id, menu]) => {
    if (menu["order"] === null) {
      configs[id]["order"] = ++order;
    }
  });

  // console.log("GetDefaultMenuConfigs()", configs);
  return configs;
};

export const GetMenuConfigsFromStorage = async () => {
  return (
    await browser.storage.sync.get({
      [CONFIG_STORAGE_KEY]: GetDefaultMenuConfigs(),
    })
  )[CONFIG_STORAGE_KEY];
};

export const GetDefaultMenuTitle = (id) =>
  browser.i18n.getMessage(`Menu_${id}_Title`);

export const GetMenuTitleForContext = (context, title) =>
  browser.i18n.getMessage(`MenuTitleForContext_${context}`, title);

export const RebuildMenus = async () => {
  await browser.contextMenus.removeAll();

  let menus = Object.values(await GetMenusWithConfigs());
  menus = menus.filter((menu) => menu.enabledContexts.length);
  menus.sort((a, b) => a["order"] - b["order"]);

  const menusByContext = {};

  Object.values(menus).forEach(
    ({ enabledContexts: contexts, order, possibleContexts, ...menu }) => {
      contexts.forEach((context) => {
        if (!menusByContext[context]) {
          menusByContext[context] = [];
        }

        menusByContext[context].push({
          ...menu,
          title: GetMenuTitleForContext(context, menu.title),
        });
      });
    }
  );

  // console.log("RebuildMenus() :: Menus By Context", menusByContext);

  Object.keys(menusByContext).forEach((context) => {
    const group = {
      id: context + "-group",
      title: browser.i18n.getMessage(`MenuGroupContextTitle_${context}`),
      contexts: [context],
    };
    // console.log("RebuildMenus() :: Creating Group", group);
    browser.contextMenus.create(group);
  });

  Object.entries(menusByContext).forEach(([context, menus]) => {
    menus.forEach(({ id, title }) => {
      if (typeof utilities[id]?.["fn"] === "function") {
        const menu = {
          parentId: context + "-group",
          id: GetMenuId(id, context),
          title,
          contexts: [context],
        };

        // console.log("RebuildMenus() :: Creating Menu", menu);
        browser.contextMenus.create(menu);
      } else {
        console.warn(`Menu ${title} does not have a valid utility function`);
      }
    });
  });
};

export const SoftResetStoredMenuConfigs = async () => {
  const { [CONFIG_STORAGE_KEY]: storedMenuConfigs = {} } =
    await browser.storage.sync.get(CONFIG_STORAGE_KEY);

  const defaultMenuConfigs = GetDefaultMenuConfigs();

  Object.keys(defaultMenuConfigs).forEach((config) => {
    if (
      storedMenuConfigs?.[config] === undefined ||
      storedMenuConfigs?.[config] === null
    ) {
      console.info(
        `Setting menu config "${config}" to default configuration`,
        defaultMenuConfigs[config]
      );

      storedMenuConfigs[config] = defaultMenuConfigs[config];
    }
  });

  Object.keys(storedMenuConfigs).forEach((config) => {
    if (
      defaultMenuConfigs[config] === undefined ||
      defaultMenuConfigs[config] === null
    ) {
      console.info(`Removing unknown/invalid menu config "${config}"`);

      delete storedMenuConfigs[config];
    }
  });

  await browser.storage.sync.set({
    [CONFIG_STORAGE_KEY]: storedMenuConfigs,
  });
};
